### PR TITLE
Support `number` alongside `string` values for the additional data

### PR DESCRIPTION
**Pull request by tp**
We needed to log numbers for range searches, e.g. statusCode > 299 or responseTimeMS > 100 etc.

### CODE REVIEW

**Review by ebeltran1981 — APPROVED** [review]
awesome! thanks for cleaning that with a `type`.

**Comment by tp** [comment]
@ebeltran1981 I wonder why values where converted to JSON twice, first before adding `message` hash and then when the whole message gets encoded again. That led to having to use `\"' for every string value in Graylog / ElasticSearch search queries.

**Comment by tp** [comment]
@ebeltran1981 I just pushed that change to not do that (works fine in our instance), but then you merged at the same time. Did you notice that and are you OK with it?

Without that change the previous one didn't have any real effect, as numbers would still be transmitted as e.g. `{ "_foo": "1" }`.

**Comment by ebeltran1981** [comment]
@tp I rewrote this library from an existing one just to have real support for TS, but I know still needs few areas to clean...

**Comment by ebeltran1981** [comment]
@tp missed your question... yes, I am OK with these changes. I just pushed the package and went out without your latest changes... will push tomorrow.

**Pull request merged**
